version: '3'
services:
  node:
    image: node:18
    user: node
    container_name: theBookers_backend
    working_dir: /app
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 3001:3001
    environment:
      MYSQL_HOST: db
      DB_NAME: theBooker_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      JWT_SECRET: batata
      MYSQL_DIALECT: mysql
      WAIT_HOSTS: db:3306
      EMAIL_PASSWORD: passwordemail
      EMAIL_USER: user@gmail.com

  db:
    image: mysql
    container_name: theBooker_db
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: password

