version: '3'
services:
  node:
    image: node:18
    user: node
    container_name: theBookers_backend
    working_dir: /app
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 3001:3001
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      JWT_SECRET: batata
      NODE_ENV: development
  
  db:
    image: mysql
    container_name: theBooker_db
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: password
networks:
  default:
    name: theBookers_net