export default [
  {
    name: 'The Catcher in the Rye',
    numberOfPages: 224,
    releaseYear: new Date(1951, 6, 16),
    author: 'J.D. Salinger',
    image: 'https://m.media-amazon.com/images/I/7108sdEUEGL.jpg',
  },
  {
    name: 'To Kill a Mockingbird',
    numberOfPages: 281,
    releaseYear: new Date(1960, 6, 11),
    author: 'Harper Lee',
    image: 'https://m.media-amazon.com/images/I/71FxgtFKcQL.jpg',
  },
  {
    name: '1984',
    numberOfPages: 328,
    releaseYear: new Date(1949, 6, 8),
    author: 'George Orwell',
    image: 'https://m.media-amazon.com/images/I/819js3EQwbL.jpg',
  },
  {
    name: 'The Great Gatsby',
    numberOfPages: 180,
    releaseYear: new Date(1925, 3, 10),
    author: 'F. Scott Fitzgerald',
    image: 'https://m.media-amazon.com/images/I/71FTb9X6wsL.jpg',
  },
  {
    name: 'Pride and Prejudice',
    numberOfPages: 279,
    releaseYear: new Date(1813, 0, 28),
    author: 'Jane Austen',
    image: 'https://m.media-amazon.com/images/I/41c4LP5otfL.jpg',
  },
  {
    name: 'Brave New World',
    numberOfPages: 311,
    releaseYear: new Date(1932, 1, 17),
    author: 'Aldous Huxley',
    image: 'https://m.media-amazon.com/images/I/91D4YvdC0dL.jpg',
  },
  {
    name: 'The Lord of the Rings',
    numberOfPages: 1178,
    releaseYear: new Date(1954, 9, 20),
    author: 'J.R.R. Tolkien',
    image: 'https://m.media-amazon.com/images/I/81nV6x2ey4L.jpg',
  },
  {
    name: 'The Hobbit',
    numberOfPages: 310,
    releaseYear: new Date(1937, 8, 21),
    author: 'J.R.R. Tolkien',
    image: 'https://m.media-amazon.com/images/I/710+HcoP38L.jpg',
  },
  {
    name: 'Animal Farm',
    numberOfPages: 112,
    releaseYear: new Date(1945, 7, 17),
    author: 'George Orwell',
    image: 'https://m.media-amazon.com/images/I/91LUbAcpACL.jpg',
  },
  {
    name: 'The Picture of Dorian Gray',
    numberOfPages: 254,
    releaseYear: new Date(1890, 0, 1),
    author: 'Oscar Wilde',
    image: 'https://m.media-amazon.com/images/I/71ZpShPyThL.jpg',
  },
  {
    name: 'Fahrenheit 451',
    numberOfPages: 174,
    releaseYear: new Date(1953, 9, 19),
    author: 'Ray Bradbury',
    image: 'https://m.media-amazon.com/images/I/51tAD6LyZ-L.jpg',
  },
  {
    name: "The Hitchhiker's Guide to the Galaxy",
    numberOfPages: 193,
    releaseYear: new Date(1979, 8, 12),
    author: 'Douglas Adams',
    image:
      'https://kbimages1-a.akamaihd.net/95611083-7f08-4a2e-893a-aca3544fd750/1200/1200/False/the-hitchhiker-s-guide-to-the-galaxy-2.jpg',
  },
];
